name: Pine Mastery CI

on:
  push:
    paths:
      - 'spec_ingest.py'
      - 'tests/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  spec-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out code
      - uses: actions/checkout@v3

      # 2. Set up Python 3.x
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Install requests library
      - name: Install requests
        run: pip install requests

            # 4. Run spec ingestion
      - name: Ingest Pine v6 spec
        run: python spec_ingest.py

      - name: Diff previous and current spec
        run: python spec_diff.py

      # 6. Generate Pine test files
      - name: Run generate_tests.py
        run: python tests/generate_tests.py

      # 4. Run spec_ingest.py (save Pine v6 docs)
      - name: Ingest spec
        run: python spec_ingest.py
      - name: Run spec_diff.py
        run: python spec_diff.py

      # 5. Run generate_tests.py (emit tests/*.pine)
      - name: Generate Pine tests
        run: python tests/generate_tests.py

      # 6. Confirm outputs
      - name: List specs and tests
        run: |
          echo "Specs directory contents:"
          ls specs
          echo "Tests directory contents:"
          ls tests
