# .github/workflows/ci.yml
name: Pine Mastery CI

on:
  push:
    paths:
      - 'spec_ingest.py'
      - 'tests/**'
      - 'harvest_scripts.py'
      - 'generate_finetune_data.py'
      - 'fine_tune.py'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install deps
        run: pip install requests beautifulsoup4 openai>=1.0.0

      - name: Ingest Pine v6 spec
        run: python spec_ingest.py

      - name: Generate Pine tests
        run: python tests/generate_tests.py

      - name: Harvest community scripts
        run: python harvest_scripts.py

      - name: Generate fine‑tune dataset
        run: python generate_finetune_data.py

      - name: Preview training set
        run: |
          echo "First 3 lines of training_dataset.jsonl:"
          head -n 3 training_dataset.jsonl

      - name: Preview validation set
        run: |
          echo "First 3 lines of validation_dataset.jsonl:"
          head -n 3 validation_dataset.jsonl

      - name: Run fine‑tune
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python fine_tune.py
