# .github/workflows/manual_run.yml
name: Manual PineScript Jobs

on:
  workflow_dispatch:
    inputs:
      fine_tune_job_id:
        description: "Fine‑tune job ID (ftjob-…)"
        required: true

jobs:
  poll-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python & deps
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install OpenAI SDK
        run: pip install openai>=1.0.0

      - name: Poll and test fine‑tuned model
        env:
          OPENAI_API_KEY:  ${{ secrets.OPENAI_API_KEY }}
          FINE_TUNE_JOB_ID: ${{ github.event.inputs.fine_tune_job_id }}
        run: python poll_and_test.py
