name: Manual PineScript Jobs

on:
  workflow_dispatch:
    inputs:
      fine_tune_id:
        description: "Fine‑tune Job ID to poll (ft‑…)"
        required: true
      model_name:
        description: "Fine‑tuned Model name (gpt‑…:ft‑…)"
        required: true

jobs:
  run-fine-tune:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install OpenAI SDK v1.x
        run: pip install "openai>=1.0.0"

      - name: Run fine‑tune
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python fine_tune.py

  poll-and-test:
    needs: run-fine-tune
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install OpenAI SDK v1.x
        run: pip install "openai>=1.0.0"

      - name: Poll fine‑tune status
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          export FINE_TUNE_ID="${{ github.event.inputs.fine_tune_id }}"
          python poll_finetune_status.py

      - name: Test fine‑tuned model
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FINE_TUNED_MODEL: ${{ github.event.inputs.model_name }}
        run: python test_finetuned_model.py
